# ANN Baseline

Baseline-ANN trainieren auf FE_v1 (ohne destinations) und evaluieren mit MAP@5 / HIT@5 wie bei LightGBM — aber mit kleinerem, stratifiziertem Sample (z.B. 300k).

## Setup

In [1]:
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
SRC_PATH = PROJECT_ROOT / "src"
fe_path = SRC_PATH / "features" / "fe_v1.py"

print("PROJECT_ROOT:", PROJECT_ROOT)
print("SRC_PATH exists:", SRC_PATH.exists())
print("fe_path:", fe_path)
print("fe_path exists:", fe_path.exists())

PROJECT_ROOT: c:\Users\Philipp\AIBootcamp\ml_project
SRC_PATH exists: True
fe_path: c:\Users\Philipp\AIBootcamp\ml_project\src\features\fe_v1.py
fe_path exists: False

In [2]:
import os, sys
from pathlib import Path
import numpy as np
import pandas as pd

# Notebook liegt in /notebooks -> Project Root ist eine Ebene höher
PROJECT_ROOT = Path.cwd().parent

# src-Ordner explizit in den Python Path aufnehmen
SRC_PATH = PROJECT_ROOT / "src"

for p in [str(PROJECT_ROOT), str(SRC_PATH)]:
    if p not in sys.path:
        sys.path.insert(0, p)

print("PROJECT_ROOT:", PROJECT_ROOT)
print("SRC_PATH:", SRC_PATH)
print("src exists:", SRC_PATH.exists())

PROJECT_ROOT: c:\Users\Philipp\AIBootcamp\ml_project
SRC_PATH: c:\Users\Philipp\AIBootcamp\ml_project\src
src exists: True

In [3]:
# src importierbar machen
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
DATA_SAMPLE = PROJECT_ROOT / "data_sample"

DATA_RAW, DATA_PROCESSED

(WindowsPath('c:/Users/Philipp/AIBootcamp/ml_project/data/raw'),
 WindowsPath('c:/Users/Philipp/AIBootcamp/ml_project/data/processed'))

In [4]:
import pandas as pd
from pathlib import Path

PROJECT_ROOT = Path.cwd().parent
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

df_path = DATA_PROCESSED / "df_model.parquet"
df = pd.read_parquet(df_path)

print("Loaded:", df_path)
print("Shape:", df.shape)
display(df.head(3))

Loaded: c:\Users\Philipp\AIBootcamp\ml_project\data\processed\df_model.parquet
Shape: (2988177, 173)

,date_time,site_name,posa_continent,user_location_country,user_location_region,user_location_city,orig_destination_distance,user_id,is_mobile,is_package,...,d140,d141,d142,d143,d144,d145,d146,d147,d148,d149
0,2014-08-11 08:22:12,2,3,66,348,48862,2234.2641,12,0,1,...,-2.384553,-2.345528,-2.396591,-2.399953,-2.388116,-2.394294,-2.400667,-2.398716,-2.386585,-2.390370
1,2014-02-27 18:01:32,2,3,66,318,52078,NaN,756,0,1,...,-2.298266,-2.145362,-2.289405,-2.299516,-2.293402,-2.298682,-2.299516,-2.293223,-2.299516,-2.217007
2,2013-06-15 15:38:05,30,4,195,548,56440,NaN,1048,0,1,...,-2.269617,-2.158832,-2.273201,-2.137717,-2.237712,-2.235306,-2.273201,-2.273201,-2.273201,-2.273201

In [5]:
# -----------------------------
# Clean dtypes (FE_v1-kompatibel)
# -----------------------------
df_clean = df.copy()

# Target als int (kleiner Typ reicht)
df_clean["hotel_cluster"] = df_clean["hotel_cluster"].astype("int32")

# bool -> int (optional, aber ANN-freundlich)
bool_cols = df_clean.select_dtypes(include=["bool"]).columns
df_clean[bool_cols] = df_clean[bool_cols].astype("int8")

# float64 -> float32 (einheitlich, speichersparend)
float64_cols = df_clean.select_dtypes(include=["float64"]).columns
df_clean[float64_cols] = df_clean[float64_cols].astype("float32")

# WICHTIG: Date-Spalten NICHT droppen oder vor-konvertieren
# fe_v1 macht pd.to_datetime selbst.
date_cols = ["date_time", "srch_ci", "srch_co"]
for c in date_cols:
    if c in df_clean.columns:
        df_clean[c] = df_clean[c].astype("string")  # NA-safe

print("Dtype counts:")
display(df_clean.dtypes.value_counts())
print("Date cols dtypes:")
display(df_clean[date_cols].dtypes)

Dtype counts:

float32    150
int64       19
string       3
int32        1
Name: count, dtype: int64

Date cols dtypes:

date_time    string[python]
srch_ci      string[python]
srch_co      string[python]
dtype: object

In [6]:
from sklearn.model_selection import train_test_split

N_SAMPLE = 300_000
df_small, _ = train_test_split(
    df_clean,
    train_size=N_SAMPLE,
    random_state=42,
    stratify=df_clean["hotel_cluster"]
)
print(df_small.shape)

(300000, 173)

## FE anwenden

In [7]:
from src.fe_v1 import make_features


X, y = make_features(df_small)

print("X shape:", X.shape)
print("y shape:", y.shape)
display(X.head(3))
print(X.dtypes)

X shape: (300000, 17)
y shape: (300000,)

,site_name,posa_continent,user_location_country,user_location_region,srch_destination_id,srch_destination_type_id,srch_adults_cnt,srch_children_cnt,srch_rm_cnt,checkin_month,length_of_stay,stay_type,is_mobile,is_package,channel,distance_missing,distance_bucket
339808,11,3,231,48,12224,6,2,1,1,8,2,short,0,0,9,True,unknown
1373819,2,3,66,337,12176,6,2,0,1,10,2,short,0,0,9,True,unknown
2246141,11,3,205,155,12269,6,2,2,1,7,2,short,0,0,5,False,mid

site_name                    int64
posa_continent               int64
user_location_country        int64
user_location_region         int64
srch_destination_id          int64
srch_destination_type_id     int64
srch_adults_cnt              int64
srch_children_cnt            int64
srch_rm_cnt                  int64
checkin_month                int64
length_of_stay               int64
stay_type                   object
is_mobile                    int64
is_package                   int64
channel                      int64
distance_missing              bool
distance_bucket             object
dtype: object

In [8]:
X = X.copy()
X["distance_missing"] = X["distance_missing"].astype("int8")

In [9]:
from sklearn.model_selection import train_test_split

SEED = 42

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=SEED,
    stratify=y
)

print(X_train.shape, X_val.shape)
print("n_classes:", y.nunique())

(240000, 17) (60000, 17)
n_classes: 100

In [10]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

cat_cols = ["stay_type", "distance_bucket"]
num_cols = [c for c in X_train.columns if c not in cat_cols]

preprocess = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), cat_cols),
        ("num", StandardScaler(with_mean=False), num_cols),  # Output bleibt sparse
    ],
    remainder="drop"
)

X_train_p = preprocess.fit_transform(X_train)
X_val_p   = preprocess.transform(X_val)

print("Processed:", X_train_p.shape, X_val_p.shape, "sparse:", hasattr(X_train_p, "toarray"))

Processed: (240000, 23) (60000, 23) sparse: False

In [11]:
import numpy as np

def hit_at_k(y_true, y_prob, k=5):
    topk = np.argsort(-y_prob, axis=1)[:, :k]
    return np.mean([yt in topk[i] for i, yt in enumerate(y_true)])

def map_at_k(y_true, y_prob, k=5):
    topk = np.argsort(-y_prob, axis=1)[:, :k]
    s = 0.0
    for i, yt in enumerate(y_true):
        row = topk[i]
        if yt in row:
            rank = np.where(row == yt)[0][0] + 1
            s += 1.0 / rank
    return s / len(y_true)

## Baseline Model Training

In [12]:
import tensorflow as tf
from tensorflow.keras import layers

tf.random.set_seed(SEED)

X_train_nn = X_train_p.toarray() if hasattr(X_train_p, "toarray") else X_train_p
X_val_nn   = X_val_p.toarray()   if hasattr(X_val_p, "toarray")   else X_val_p

n_classes = int(np.max(y_train) + 1)

model = tf.keras.Sequential([
    layers.Input(shape=(X_train_nn.shape[1],)),
    layers.Dense(256, activation="relu"),
    layers.Dropout(0.3),
    layers.Dense(n_classes, activation="softmax")
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"]
)

model.summary()

WARNING:tensorflow:From c:\Users\Philipp\AIBootcamp\ml_project\.venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

WARNING:tensorflow:From c:\Users\Philipp\AIBootcamp\ml_project\.venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 256)               6144

 dropout (Dropout)           (None, 256)               0

 dense_1 (Dense)             (None, 100)               25700

=================================================================
Total params: 31844 (124.39 KB)
Trainable params: 31844 (124.39 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2, min_lr=1e-5),
]

history = model.fit(
    X_train_nn, y_train,
    validation_data=(X_val_nn, y_val),
    epochs=15,
    batch_size=2048,
    callbacks=callbacks,
    verbose=1
)

Epoch 1/15
WARNING:tensorflow:From c:\Users\Philipp\AIBootcamp\ml_project\.venv\Lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\Philipp\AIBootcamp\ml_project\.venv\Lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

118/118 [==============================] - 1s 7ms/step - loss: 4.3638 - sparse_categorical_accuracy: 0.0419 - val_loss: 4.2233 - val_sparse_categorical_accuracy: 0.0556 - lr: 0.0010
Epoch 2/15
118/118 [==============================] - 1s 5ms/step - loss: 4.2162 - sparse_categorical_accuracy: 0.0537 - val_loss: 4.1718 - val_sparse_categorical_accuracy: 0.0595 - lr: 0.0010
Epoch 3/15
118/118 [==============================] - 1s 5ms/step - loss: 4.1800 - sparse_categorical_accuracy: 0.0573 - val_loss: 4.1549 - val_sparse_categorical_accuracy: 0.0608 - lr: 0.0010
Epoch 4/15
118/118 [==============================] - 1s 5ms/step - loss: 4.1620 - sparse_categorical_accuracy: 0.0588 - val_loss: 4.1427 - val_sparse_categorical_accuracy: 0.0622 - lr: 0.0010
Epoch 5/15
118/118 [==============================] - 1s 5ms/step - loss: 4.1488 - sparse_categorical_accuracy: 0.0605 - val_loss: 4.1326 - val_sparse_categorical_accuracy: 0.0624 - lr: 0.0010
Epoch 6/15
118/118 [==============================] - 1s 5ms/step - loss: 4.1385 - sparse_categorical_accuracy: 0.0609 - val_loss: 4.1254 - val_sparse_categorical_accuracy: 0.0624 - lr: 0.0010
Epoch 7/15
118/118 [==============================] - 1s 5ms/step - loss: 4.1300 - sparse_categorical_accuracy: 0.0619 - val_loss: 4.1184 - val_sparse_categorical_accuracy: 0.0632 - lr: 0.0010
Epoch 8/15
118/118 [==============================] - 1s 5ms/step - loss: 4.1218 - sparse_categorical_accuracy: 0.0623 - val_loss: 4.1110 - val_sparse_categorical_accuracy: 0.0635 - lr: 0.0010
Epoch 9/15
118/118 [==============================] - 1s 5ms/step - loss: 4.1143 - sparse_categorical_accuracy: 0.0629 - val_loss: 4.1045 - val_sparse_categorical_accuracy: 0.0646 - lr: 0.0010
Epoch 10/15
118/118 [==============================] - 1s 5ms/step - loss: 4.1058 - sparse_categorical_accuracy: 0.0639 - val_loss: 4.0968 - val_sparse_categorical_accuracy: 0.0654 - lr: 0.0010
Epoch 11/15
118/118 [==============================] - 1s 5ms/step - loss: 4.0972 - sparse_categorical_accuracy: 0.0648 - val_loss: 4.0877 - val_sparse_categorical_accuracy: 0.0653 - lr: 0.0010
Epoch 12/15
118/118 [==============================] - 1s 5ms/step - loss: 4.0893 - sparse_categorical_accuracy: 0.0649 - val_loss: 4.0782 - val_sparse_categorical_accuracy: 0.0662 - lr: 0.0010
Epoch 13/15
118/118 [==============================] - 1s 5ms/step - loss: 4.0803 - sparse_categorical_accuracy: 0.0662 - val_loss: 4.0709 - val_sparse_categorical_accuracy: 0.0671 - lr: 0.0010
Epoch 14/15
118/118 [==============================] - 1s 5ms/step - loss: 4.0740 - sparse_categorical_accuracy: 0.0665 - val_loss: 4.0650 - val_sparse_categorical_accuracy: 0.0669 - lr: 0.0010
Epoch 15/15
118/118 [==============================] - 1s 5ms/step - loss: 4.0674 - sparse_categorical_accuracy: 0.0671 - val_loss: 4.0601 - val_sparse_categorical_accuracy: 0.0673 - lr: 0.0010

## Evaluation

In [14]:
y_val_prob = model.predict(X_val_nn, batch_size=4096, verbose=0)

y_val_arr = y_val.to_numpy() if hasattr(y_val, "to_numpy") else np.asarray(y_val)

print("HIT@5:", hit_at_k(y_val_arr, y_val_prob, k=5))
print("MAP@5:", map_at_k(y_val_arr, y_val_prob, k=5))

HIT@5: 0.22798333333333334
MAP@5: 0.1213949999999917

## 1st Iteration - more capacity + batchnorm

In [15]:
import tensorflow as tf
from tensorflow.keras import layers, regularizers

tf.random.set_seed(SEED)

model = tf.keras.Sequential([
    layers.Input(shape=(X_train_nn.shape[1],)),

    layers.Dense(512, activation="relu", kernel_regularizer=regularizers.l2(1e-5)),
    layers.BatchNormalization(),
    layers.Dropout(0.35),

    layers.Dense(256, activation="relu", kernel_regularizer=regularizers.l2(1e-5)),
    layers.BatchNormalization(),
    layers.Dropout(0.30),

    layers.Dense(n_classes, activation="softmax")
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=8e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"]
)
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 512)               12288

 batch_normalization (Batch  (None, 512)               2048
 Normalization)

 dropout_1 (Dropout)         (None, 512)               0

 dense_3 (Dense)             (None, 256)               131328

 batch_normalization_1 (Bat  (None, 256)               1024
 chNormalization)

 dropout_2 (Dropout)         (None, 256)               0

 dense_4 (Dense)             (None, 100)               25700

=================================================================
Total params: 172388 (673.39 KB)
Trainable params: 170852 (667.39 KB)
Non-trainable params: 1536 (6.00 KB)
_________________________________________________________________

In [17]:
import tensorflow as tf

y_train_oh = tf.keras.utils.to_categorical(y_train, num_classes=n_classes)
y_val_oh   = tf.keras.utils.to_categorical(y_val,   num_classes=n_classes)

In [18]:
loss = tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.05)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=8e-4),
    loss=loss,
    metrics=["categorical_accuracy"]
)

In [19]:
history = model.fit(
    X_train_nn, y_train_oh,
    validation_data=(X_val_nn, y_val_oh),
    epochs=15,
    batch_size=2048,
    callbacks=callbacks,
    verbose=1
)

Epoch 1/15
118/118 [==============================] - 3s 15ms/step - loss: 4.7592 - categorical_accuracy: 0.0339 - val_loss: 4.3720 - val_categorical_accuracy: 0.0522 - lr: 8.0000e-04
Epoch 2/15
118/118 [==============================] - 2s 14ms/step - loss: 4.4103 - categorical_accuracy: 0.0459 - val_loss: 4.2507 - val_categorical_accuracy: 0.0594 - lr: 8.0000e-04
Epoch 3/15
118/118 [==============================] - 2s 14ms/step - loss: 4.3061 - categorical_accuracy: 0.0516 - val_loss: 4.2063 - val_categorical_accuracy: 0.0614 - lr: 8.0000e-04
Epoch 4/15
118/118 [==============================] - 2s 14ms/step - loss: 4.2589 - categorical_accuracy: 0.0553 - val_loss: 4.1819 - val_categorical_accuracy: 0.0634 - lr: 8.0000e-04
Epoch 5/15
118/118 [==============================] - 2s 14ms/step - loss: 4.2280 - categorical_accuracy: 0.0586 - val_loss: 4.1695 - val_categorical_accuracy: 0.0636 - lr: 8.0000e-04
Epoch 6/15
118/118 [==============================] - 2s 14ms/step - loss: 4.2037 - categorical_accuracy: 0.0600 - val_loss: 4.1524 - val_categorical_accuracy: 0.0650 - lr: 8.0000e-04
Epoch 7/15
118/118 [==============================] - 2s 14ms/step - loss: 4.1755 - categorical_accuracy: 0.0628 - val_loss: 4.1304 - val_categorical_accuracy: 0.0661 - lr: 8.0000e-04
Epoch 8/15
118/118 [==============================] - 2s 15ms/step - loss: 4.1525 - categorical_accuracy: 0.0643 - val_loss: 4.1078 - val_categorical_accuracy: 0.0672 - lr: 8.0000e-04
Epoch 9/15
118/118 [==============================] - 2s 14ms/step - loss: 4.1365 - categorical_accuracy: 0.0656 - val_loss: 4.0964 - val_categorical_accuracy: 0.0689 - lr: 8.0000e-04
Epoch 10/15
118/118 [==============================] - 2s 15ms/step - loss: 4.1228 - categorical_accuracy: 0.0666 - val_loss: 4.0909 - val_categorical_accuracy: 0.0694 - lr: 8.0000e-04
Epoch 11/15
118/118 [==============================] - 2s 14ms/step - loss: 4.1111 - categorical_accuracy: 0.0676 - val_loss: 4.0774 - val_categorical_accuracy: 0.0707 - lr: 8.0000e-04
Epoch 12/15
118/118 [==============================] - 2s 15ms/step - loss: 4.1032 - categorical_accuracy: 0.0686 - val_loss: 4.0729 - val_categorical_accuracy: 0.0703 - lr: 8.0000e-04
Epoch 13/15
118/118 [==============================] - 2s 15ms/step - loss: 4.0951 - categorical_accuracy: 0.0692 - val_loss: 4.0664 - val_categorical_accuracy: 0.0712 - lr: 8.0000e-04
Epoch 14/15
118/118 [==============================] - 2s 15ms/step - loss: 4.0880 - categorical_accuracy: 0.0700 - val_loss: 4.0628 - val_categorical_accuracy: 0.0715 - lr: 8.0000e-04
Epoch 15/15
118/118 [==============================] - 2s 15ms/step - loss: 4.0812 - categorical_accuracy: 0.0703 - val_loss: 4.0571 - val_categorical_accuracy: 0.0729 - lr: 8.0000e-04

In [21]:
y_val_prob = model.predict(X_val_nn, batch_size=4096, verbose=0)

y_val_arr = y_val.to_numpy() if hasattr(y_val, "to_numpy") else np.asarray(y_val)

print("HIT@5:", hit_at_k(y_val_arr, y_val_prob, k=5))
print("MAP@5:", map_at_k(y_val_arr, y_val_prob, k=5))

HIT@5: 0.24761666666666668
MAP@5: 0.13161083333332355

## Embeddings

In [22]:
from sklearn.model_selection import train_test_split

SEED = 42

X = X.copy()
X["distance_missing"] = X["distance_missing"].astype("int8")  # wichtig

X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=SEED,
    stratify=y
)

n_classes = int(y_train.max() + 1)
print(X_train.shape, X_val.shape, "n_classes:", n_classes)

(240000, 17) (60000, 17) n_classes: 100

In [23]:
int_cat_cols = [
    "site_name",
    "posa_continent",
    "user_location_country",
    "user_location_region",
    "srch_destination_id",
    "srch_destination_type_id",
    "channel",
]

str_cat_cols = ["stay_type", "distance_bucket"]

num_cols = [
    "srch_adults_cnt",
    "srch_children_cnt",
    "srch_rm_cnt",
    "checkin_month",
    "length_of_stay",
    "is_mobile",
    "is_package",
    "distance_missing",
]

# sanity
for c in int_cat_cols + str_cat_cols + num_cols:
    assert c in X_train.columns, f"Missing column: {c}"

In [29]:
import tensorflow as tf
import numpy as np

def df_to_dict(df):
    out = {}

    # int categorical (1D)
    for c in int_cat_cols:
        out[c] = df[c].astype("int32").to_numpy()

    # string categorical (1D)
    for c in str_cat_cols:
        out[c] = df[c].astype(str).to_numpy()

    # numeric as ONE vector input called "num"
    out["num"] = df[num_cols].astype("float32").to_numpy()

    return out


BATCH = 4096

train_ds = tf.data.Dataset.from_tensor_slices((df_to_dict(X_train), y_train.astype("int32").to_numpy()))
val_ds   = tf.data.Dataset.from_tensor_slices((df_to_dict(X_val),   y_val.astype("int32").to_numpy()))

train_ds = train_ds.shuffle(200_000, seed=SEED).batch(BATCH).prefetch(tf.data.AUTOTUNE)
val_ds   = val_ds.batch(BATCH).prefetch(tf.data.AUTOTUNE)

In [30]:
batch_x, batch_y = next(iter(train_ds))
print(batch_x.keys())
print("num shape:", batch_x["num"].shape)

dict_keys(['site_name', 'posa_continent', 'user_location_country', 'user_location_region', 'srch_destination_id', 'srch_destination_type_id', 'channel', 'stay_type', 'distance_bucket', 'num'])
num shape: (4096, 8)

In [31]:
# Integer lookups
int_lookups = {}
for c in int_cat_cols:
    layer = tf.keras.layers.IntegerLookup(output_mode="int", mask_value=-1)  # -1 als unknown
    layer.adapt(X_train[c].astype("int32").to_numpy())
    int_lookups[c] = layer

# String lookups
str_lookups = {}
for c in str_cat_cols:
    layer = tf.keras.layers.StringLookup(output_mode="int", mask_token=None)  # unknown wird automatisch gehandhabt
    layer.adapt(X_train[c].astype(str).to_numpy())
    str_lookups[c] = layer

# Normalization für numerische Features (als Vektor)
norm = tf.keras.layers.Normalization(axis=-1)
norm.adapt(X_train[num_cols].astype("float32").to_numpy())

In [32]:
import math

def emb_dim(vocab_size):
    return int(min(50, round(math.sqrt(vocab_size)) + 1))

vocab_sizes = {}
for c, lk in int_lookups.items():
    vocab_sizes[c] = lk.vocabulary_size()
for c, lk in str_lookups.items():
    vocab_sizes[c] = lk.vocabulary_size()

for k,v in vocab_sizes.items():
    print(k, "vocab:", v, "dim:", emb_dim(v))

site_name vocab: 44 dim: 8
posa_continent vocab: 7 dim: 4
user_location_country vocab: 210 dim: 15
user_location_region vocab: 828 dim: 30
srch_destination_id vocab: 15231 dim: 50
srch_destination_type_id vocab: 7 dim: 4
channel vocab: 13 dim: 5
stay_type vocab: 4 dim: 3
distance_bucket vocab: 6 dim: 3

In [33]:
from tensorflow.keras import layers

inputs = {}
embeddings = []

# integer categorical -> lookup -> embedding
for c in int_cat_cols:
    inp = tf.keras.Input(shape=(1,), name=c, dtype=tf.int32)
    inputs[c] = inp
    x = int_lookups[c](inp)
    v = int_lookups[c].vocabulary_size()
    e = layers.Embedding(input_dim=v, output_dim=emb_dim(v), name=f"emb_{c}")(x)
    e = layers.Reshape((emb_dim(v),))(e)
    embeddings.append(e)

# string categorical -> lookup -> embedding
for c in str_cat_cols:
    inp = tf.keras.Input(shape=(1,), name=c, dtype=tf.string)
    inputs[c] = inp
    x = str_lookups[c](inp)
    v = str_lookups[c].vocabulary_size()
    e = layers.Embedding(input_dim=v, output_dim=emb_dim(v), name=f"emb_{c}")(x)
    e = layers.Reshape((emb_dim(v),))(e)
    embeddings.append(e)

# numeric -> normalization
num_inp = tf.keras.Input(shape=(len(num_cols),), name="num", dtype=tf.float32)
inputs["num"] = num_inp
num_x = norm(num_inp)

# concat all
x = layers.Concatenate()(embeddings + [num_x])

# dense trunk
x = layers.Dense(512, activation="relu")(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(0.35)(x)

x = layers.Dense(256, activation="relu")(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(0.30)(x)

out = layers.Dense(n_classes, activation="softmax")(x)

model = tf.keras.Model(inputs=inputs, outputs=out)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=8e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 site_name (InputLayer)      [(None, 1)]                  0         []

 posa_continent (InputLayer  [(None, 1)]                  0         []
 )

 user_location_country (Inp  [(None, 1)]                  0         []
 utLayer)

 user_location_region (Inpu  [(None, 1)]                  0         []
 tLayer)

 srch_destination_id (Input  [(None, 1)]                  0         []
 Layer)

 srch_destination_type_id (  [(None, 1)]                  0         []
 InputLayer)

 channel (InputLayer)        [(None, 1)]                  0         []

 stay_type (InputLayer)      [(None, 1)]                  0         []

 distance_bucket (InputLaye  [(None, 1)]                  0         []
 r)

 integer_lookup_7 (IntegerL  (None, 1)                    0         ['site_name[0][0]']
 ookup)

 integer_lookup_8 (IntegerL  (None, 1)                    0         ['posa_continent[0][0]']
 ookup)

 integer_lookup_9 (IntegerL  (None, 1)                    0         ['user_location_country[0][0]'
 ookup)                                                             ]

 integer_lookup_10 (Integer  (None, 1)                    0         ['user_location_region[0][0]']
 Lookup)

 integer_lookup_11 (Integer  (None, 1)                    0         ['srch_destination_id[0][0]']
 Lookup)

 integer_lookup_12 (Integer  (None, 1)                    0         ['srch_destination_type_id[0][
 Lookup)                                                            0]']

 integer_lookup_13 (Integer  (None, 1)                    0         ['channel[0][0]']
 Lookup)

 string_lookup_2 (StringLoo  (None, 1)                    0         ['stay_type[0][0]']
 kup)

 string_lookup_3 (StringLoo  (None, 1)                    0         ['distance_bucket[0][0]']
 kup)

 emb_site_name (Embedding)   (None, 1, 8)                 352       ['integer_lookup_7[0][0]']

 emb_posa_continent (Embedd  (None, 1, 4)                 28        ['integer_lookup_8[0][0]']
 ing)

 emb_user_location_country   (None, 1, 15)                3150      ['integer_lookup_9[0][0]']
 (Embedding)

 emb_user_location_region (  (None, 1, 30)                24840     ['integer_lookup_10[0][0]']
 Embedding)

 emb_srch_destination_id (E  (None, 1, 50)                761550    ['integer_lookup_11[0][0]']
 mbedding)

 emb_srch_destination_type_  (None, 1, 4)                 28        ['integer_lookup_12[0][0]']
 id (Embedding)

 emb_channel (Embedding)     (None, 1, 5)                 65        ['integer_lookup_13[0][0]']

 emb_stay_type (Embedding)   (None, 1, 3)                 12        ['string_lookup_2[0][0]']

 emb_distance_bucket (Embed  (None, 1, 3)                 18        ['string_lookup_3[0][0]']
 ding)

 num (InputLayer)            [(None, 8)]                  0         []

 reshape_9 (Reshape)         (None, 8)                    0         ['emb_site_name[0][0]']

 reshape_10 (Reshape)        (None, 4)                    0         ['emb_posa_continent[0][0]']

 reshape_11 (Reshape)        (None, 15)                   0         ['emb_user_location_country[0]
                                                                    [0]']

 reshape_12 (Reshape)        (None, 30)                   0         ['emb_user_location_region[0][
                                                                    0]']

 reshape_13 (Reshape)        (None, 50)                   0         ['emb_srch_destination_id[0][0
                                                                    ]']

 reshape_14 (Reshape)        (None, 4)                    0         ['emb_srch_destination_type_id
                                                                    [0][0]']

 reshape_15 (Reshape)        (None, 5)                    0         ['emb_channel[0][0]']

 reshape_16 (Reshape)        (None, 3)                    0         ['emb_stay_type[0][0]']

 reshape_17 (Reshape)        (None, 3)                    0         ['emb_distance_bucket[0][0]']

 normalization_1 (Normaliza  (None, 8)                    17        ['num[0][0]']
 tion)

 concatenate_1 (Concatenate  (None, 130)                  0         ['reshape_9[0][0]',
 )                                                                   'reshape_10[0][0]',
                                                                     'reshape_11[0][0]',
                                                                     'reshape_12[0][0]',
                                                                     'reshape_13[0][0]',
                                                                     'reshape_14[0][0]',
                                                                     'reshape_15[0][0]',
                                                                     'reshape_16[0][0]',
                                                                     'reshape_17[0][0]',
                                                                     'normalization_1[0][0]']

 dense_8 (Dense)             (None, 512)                  67072     ['concatenate_1[0][0]']

 batch_normalization_4 (Bat  (None, 512)                  2048      ['dense_8[0][0]']
 chNormalization)

 dropout_5 (Dropout)         (None, 512)                  0         ['batch_normalization_4[0][0]'
                                                                    ]

 dense_9 (Dense)             (None, 256)                  131328    ['dropout_5[0][0]']

 batch_normalization_5 (Bat  (None, 256)                  1024      ['dense_9[0][0]']
 chNormalization)

 dropout_6 (Dropout)         (None, 256)                  0         ['batch_normalization_5[0][0]'
                                                                    ]

 dense_10 (Dense)            (None, 100)                  25700     ['dropout_6[0][0]']

==================================================================================================
Total params: 1017232 (3.88 MB)
Trainable params: 1015679 (3.87 MB)
Non-trainable params: 1553 (6.07 KB)
__________________________________________________________________________________________________

## 2 iteration with embedded features

In [34]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2, min_lr=1e-5),
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    callbacks=callbacks,
    verbose=1
)

Epoch 1/20

59/59 [==============================] - 5s 59ms/step - loss: 4.8457 - sparse_categorical_accuracy: 0.0297 - val_loss: 4.4640 - val_sparse_categorical_accuracy: 0.0471 - lr: 8.0000e-04
Epoch 2/20
59/59 [==============================] - 4s 54ms/step - loss: 4.2965 - sparse_categorical_accuracy: 0.0604 - val_loss: 4.2374 - val_sparse_categorical_accuracy: 0.0630 - lr: 8.0000e-04
Epoch 3/20
59/59 [==============================] - 4s 54ms/step - loss: 3.8429 - sparse_categorical_accuracy: 0.0902 - val_loss: 4.0664 - val_sparse_categorical_accuracy: 0.0652 - lr: 8.0000e-04
Epoch 4/20
59/59 [==============================] - 4s 58ms/step - loss: 3.5827 - sparse_categorical_accuracy: 0.1189 - val_loss: 3.9613 - val_sparse_categorical_accuracy: 0.0703 - lr: 8.0000e-04
Epoch 5/20
59/59 [==============================] - 5s 68ms/step - loss: 3.4101 - sparse_categorical_accuracy: 0.1457 - val_loss: 3.8440 - val_sparse_categorical_accuracy: 0.0938 - lr: 8.0000e-04
Epoch 6/20
59/59 [==============================] - 5s 73ms/step - loss: 3.2819 - sparse_categorical_accuracy: 0.1706 - val_loss: 3.7197 - val_sparse_categorical_accuracy: 0.1151 - lr: 8.0000e-04
Epoch 7/20
59/59 [==============================] - 5s 73ms/step - loss: 3.1758 - sparse_categorical_accuracy: 0.1914 - val_loss: 3.5712 - val_sparse_categorical_accuracy: 0.1387 - lr: 8.0000e-04
Epoch 8/20
59/59 [==============================] - 5s 76ms/step - loss: 3.0895 - sparse_categorical_accuracy: 0.2066 - val_loss: 3.4470 - val_sparse_categorical_accuracy: 0.1553 - lr: 8.0000e-04
Epoch 9/20
59/59 [==============================] - 5s 77ms/step - loss: 3.0207 - sparse_categorical_accuracy: 0.2156 - val_loss: 3.3320 - val_sparse_categorical_accuracy: 0.1722 - lr: 8.0000e-04
Epoch 10/20
59/59 [==============================] - 5s 74ms/step - loss: 2.9654 - sparse_categorical_accuracy: 0.2226 - val_loss: 3.2637 - val_sparse_categorical_accuracy: 0.1761 - lr: 8.0000e-04
Epoch 11/20
59/59 [==============================] - 5s 73ms/step - loss: 2.9229 - sparse_categorical_accuracy: 0.2266 - val_loss: 3.2264 - val_sparse_categorical_accuracy: 0.1804 - lr: 8.0000e-04
Epoch 12/20
59/59 [==============================] - 5s 73ms/step - loss: 2.8885 - sparse_categorical_accuracy: 0.2282 - val_loss: 3.2086 - val_sparse_categorical_accuracy: 0.1814 - lr: 8.0000e-04
Epoch 13/20
59/59 [==============================] - 5s 75ms/step - loss: 2.8615 - sparse_categorical_accuracy: 0.2309 - val_loss: 3.2094 - val_sparse_categorical_accuracy: 0.1818 - lr: 8.0000e-04
Epoch 14/20
59/59 [==============================] - 5s 75ms/step - loss: 2.8358 - sparse_categorical_accuracy: 0.2337 - val_loss: 3.2154 - val_sparse_categorical_accuracy: 0.1826 - lr: 8.0000e-04
Epoch 15/20
59/59 [==============================] - 5s 74ms/step - loss: 2.7917 - sparse_categorical_accuracy: 0.2414 - val_loss: 3.2181 - val_sparse_categorical_accuracy: 0.1830 - lr: 4.0000e-04

In [35]:
y_val_prob = model.predict(val_ds, verbose=0)

y_val_arr = y_val.to_numpy() if hasattr(y_val, "to_numpy") else np.asarray(y_val)

print("HIT@5:", hit_at_k(y_val_arr, y_val_prob, k=5))
print("MAP@5:", map_at_k(y_val_arr, y_val_prob, k=5))

HIT@5: 0.49398333333333333
MAP@5: 0.2917075000000289

## 3. Iteration 500k

In [37]:
from sklearn.model_selection import train_test_split

SEED = 42
df_500k, _ = train_test_split(
    df_clean,
    train_size=500_000,
    random_state=SEED,
    stratify=df_clean["hotel_cluster"]
)

In [38]:
X, y = make_features(df_500k)
X["distance_missing"] = X["distance_missing"].astype("int8")

In [39]:
X_train, X_val, y_train, y_val = train_test_split(
    X, y,
    test_size=0.2,
    random_state=SEED,
    stratify=y
)

n_classes = int(y_train.max() + 1)

In [40]:
train_ds = tf.data.Dataset.from_tensor_slices(
    (df_to_dict(X_train), y_train.astype("int32").to_numpy())
).shuffle(200_000, seed=SEED).batch(BATCH).prefetch(tf.data.AUTOTUNE)

val_ds = tf.data.Dataset.from_tensor_slices(
    (df_to_dict(X_val), y_val.astype("int32").to_numpy())
).batch(BATCH).prefetch(tf.data.AUTOTUNE)

In [41]:
# int_lookups adapt
for c in int_cat_cols:
    int_lookups[c].adapt(X_train[c].astype("int32").to_numpy())

# str_lookups adapt
for c in str_cat_cols:
    str_lookups[c].adapt(X_train[c].astype(str).to_numpy())

# norm adapt
norm.adapt(X_train[num_cols].astype("float32").to_numpy())

In [42]:
history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    callbacks=callbacks,
    verbose=1
)

Epoch 1/20
98/98 [==============================] - 7s 68ms/step - loss: 3.0737 - sparse_categorical_accuracy: 0.2013 - val_loss: 2.9547 - val_sparse_categorical_accuracy: 0.2189 - lr: 4.0000e-04
Epoch 2/20
98/98 [==============================] - 8s 70ms/step - loss: 3.0162 - sparse_categorical_accuracy: 0.2065 - val_loss: 2.9505 - val_sparse_categorical_accuracy: 0.2158 - lr: 4.0000e-04
Epoch 3/20
98/98 [==============================] - 7s 69ms/step - loss: 2.9837 - sparse_categorical_accuracy: 0.2086 - val_loss: 2.9504 - val_sparse_categorical_accuracy: 0.2129 - lr: 4.0000e-04
Epoch 4/20
98/98 [==============================] - 8s 70ms/step - loss: 2.9585 - sparse_categorical_accuracy: 0.2105 - val_loss: 2.9513 - val_sparse_categorical_accuracy: 0.2108 - lr: 4.0000e-04
Epoch 5/20
98/98 [==============================] - 8s 71ms/step - loss: 2.9408 - sparse_categorical_accuracy: 0.2123 - val_loss: 2.9515 - val_sparse_categorical_accuracy: 0.2100 - lr: 4.0000e-04
Epoch 6/20
98/98 [==============================] - 8s 71ms/step - loss: 2.9134 - sparse_categorical_accuracy: 0.2160 - val_loss: 2.9494 - val_sparse_categorical_accuracy: 0.2096 - lr: 2.0000e-04
Epoch 7/20
98/98 [==============================] - 8s 71ms/step - loss: 2.9031 - sparse_categorical_accuracy: 0.2169 - val_loss: 2.9497 - val_sparse_categorical_accuracy: 0.2087 - lr: 2.0000e-04
Epoch 8/20
98/98 [==============================] - 8s 73ms/step - loss: 2.8954 - sparse_categorical_accuracy: 0.2173 - val_loss: 2.9504 - val_sparse_categorical_accuracy: 0.2084 - lr: 2.0000e-04
Epoch 9/20
98/98 [==============================] - 8s 72ms/step - loss: 2.8820 - sparse_categorical_accuracy: 0.2190 - val_loss: 2.9503 - val_sparse_categorical_accuracy: 0.2083 - lr: 1.0000e-04

In [43]:
y_val_prob = model.predict(val_ds, verbose=0)
y_val_arr = y_val.to_numpy() if hasattr(y_val, "to_numpy") else np.asarray(y_val)

print("HIT@5:", hit_at_k(y_val_arr, y_val_prob, k=5))
print("MAP@5:", map_at_k(y_val_arr, y_val_prob, k=5))

HIT@5: 0.55329
MAP@5: 0.3320191666666517

In [58]:
from pathlib import Path

# Project root (falls noch nicht definiert)
PROJECT_ROOT = Path.cwd().parent  # Notebook liegt in /notebooks

MODEL_DIR = PROJECT_ROOT / "models"
MODEL_DIR.mkdir(exist_ok=True)

save_path = MODEL_DIR / "ann_embeddings_fe_v1_500k_final"
model.save(save_path)

print("Saved:", save_path)

INFO:tensorflow:Assets written to: c:\Users\Philipp\AIBootcamp\ml_project\models\ann_embeddings_fe_v1_500k_final\assets

INFO:tensorflow:Assets written to: c:\Users\Philipp\AIBootcamp\ml_project\models\ann_embeddings_fe_v1_500k_final\assets

Saved: c:\Users\Philipp\AIBootcamp\ml_project\models\ann_embeddings_fe_v1_500k_final

## 4. Iteration mit 500k und FE_v2

In [44]:
from sklearn.model_selection import train_test_split

SEED = 42
df_500k, _ = train_test_split(
    df_clean,
    train_size=500_000,
    random_state=SEED,
    stratify=df_clean["hotel_cluster"]
)

In [45]:
from src.fe_v2 import make_features

X, y = make_features(df_500k)
X["distance_missing"] = X["distance_missing"].astype("int8")

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=SEED,
    stratify=y
)

print("X_train shape:", X_train.shape)

X_train shape: (400000, 166)

In [50]:
import re

# destination latent features
dest_cols = [c for c in X.columns if re.fullmatch(r"d\d+", c)]

num_cols = [
    "srch_adults_cnt",
    "srch_children_cnt",
    "srch_rm_cnt",
    "checkin_month",
    "length_of_stay",
    "is_mobile",
    "is_package",
    "distance_missing",
] + dest_cols

In [51]:
norm = tf.keras.layers.Normalization(axis=-1)
norm.adapt(X_train[num_cols].astype("float32").to_numpy())

In [52]:
BATCH = 4096

train_ds = tf.data.Dataset.from_tensor_slices(
    (df_to_dict(X_train), y_train.astype("int32").to_numpy())
).shuffle(200_000, seed=SEED).batch(BATCH).prefetch(tf.data.AUTOTUNE)

val_ds = tf.data.Dataset.from_tensor_slices(
    (df_to_dict(X_val), y_val.astype("int32").to_numpy())
).batch(BATCH).prefetch(tf.data.AUTOTUNE)

In [53]:
# Integer lookups
int_lookups = {}
for c in int_cat_cols:
    lk = tf.keras.layers.IntegerLookup(output_mode="int", mask_value=-1)
    lk.adapt(X_train[c].astype("int32").to_numpy())
    int_lookups[c] = lk

# String lookups
str_lookups = {}
for c in str_cat_cols:
    lk = tf.keras.layers.StringLookup(output_mode="int", mask_token=None)
    lk.adapt(X_train[c].astype(str).to_numpy())
    str_lookups[c] = lk

WARNING:tensorflow:mask_value is deprecated, use mask_token instead.

In [54]:
import math
from tensorflow.keras import layers

def emb_dim(vocab):
    return int(min(50, round(math.sqrt(vocab)) + 1))

inputs = {}
embeddings = []

# int categorical embeddings
for c in int_cat_cols:
    inp = tf.keras.Input(shape=(1,), name=c, dtype=tf.int32)
    inputs[c] = inp
    x = int_lookups[c](inp)
    v = int_lookups[c].vocabulary_size()
    out_dim = 64 if c == "srch_destination_id" else emb_dim(v)
    e = layers.Embedding(v, out_dim)(x)
    e = layers.Reshape((out_dim,))(e)
    embeddings.append(e)

# string categorical embeddings
for c in str_cat_cols:
    inp = tf.keras.Input(shape=(1,), name=c, dtype=tf.string)
    inputs[c] = inp
    x = str_lookups[c](inp)
    v = str_lookups[c].vocabulary_size()
    e = layers.Embedding(v, emb_dim(v))(x)
    e = layers.Reshape((emb_dim(v),))(e)
    embeddings.append(e)

# numeric block
num_inp = tf.keras.Input(shape=(len(num_cols),), name="num", dtype=tf.float32)
inputs["num"] = num_inp
num_x = norm(num_inp)

# concat
x = layers.Concatenate()(embeddings + [num_x])
x = layers.Dense(512, activation="relu")(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(0.35)(x)
x = layers.Dense(256, activation="relu")(x)
x = layers.BatchNormalization()(x)
x = layers.Dropout(0.30)(x)

out = layers.Dense(n_classes, activation="softmax")(x)

model = tf.keras.Model(inputs, out)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=8e-4),
    loss="sparse_categorical_crossentropy",
    metrics=["sparse_categorical_accuracy"],
)

model.summary()

Model: "model_2"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 site_name (InputLayer)      [(None, 1)]                  0         []

 posa_continent (InputLayer  [(None, 1)]                  0         []
 )

 user_location_country (Inp  [(None, 1)]                  0         []
 utLayer)

 user_location_region (Inpu  [(None, 1)]                  0         []
 tLayer)

 srch_destination_id (Input  [(None, 1)]                  0         []
 Layer)

 srch_destination_type_id (  [(None, 1)]                  0         []
 InputLayer)

 channel (InputLayer)        [(None, 1)]                  0         []

 stay_type (InputLayer)      [(None, 1)]                  0         []

 distance_bucket (InputLaye  [(None, 1)]                  0         []
 r)

 integer_lookup_14 (Integer  (None, 1)                    0         ['site_name[0][0]']
 Lookup)

 integer_lookup_15 (Integer  (None, 1)                    0         ['posa_continent[0][0]']
 Lookup)

 integer_lookup_16 (Integer  (None, 1)                    0         ['user_location_country[0][0]'
 Lookup)                                                            ]

 integer_lookup_17 (Integer  (None, 1)                    0         ['user_location_region[0][0]']
 Lookup)

 integer_lookup_18 (Integer  (None, 1)                    0         ['srch_destination_id[0][0]']
 Lookup)

 integer_lookup_19 (Integer  (None, 1)                    0         ['srch_destination_type_id[0][
 Lookup)                                                            0]']

 integer_lookup_20 (Integer  (None, 1)                    0         ['channel[0][0]']
 Lookup)

 string_lookup_4 (StringLoo  (None, 1)                    0         ['stay_type[0][0]']
 kup)

 string_lookup_5 (StringLoo  (None, 1)                    0         ['distance_bucket[0][0]']
 kup)

 embedding (Embedding)       (None, 1, 8)                 352       ['integer_lookup_14[0][0]']

 embedding_1 (Embedding)     (None, 1, 4)                 28        ['integer_lookup_15[0][0]']

 embedding_2 (Embedding)     (None, 1, 16)                3536      ['integer_lookup_16[0][0]']

 embedding_3 (Embedding)     (None, 1, 31)                27156     ['integer_lookup_17[0][0]']

 embedding_4 (Embedding)     (None, 1, 64)                1195584   ['integer_lookup_18[0][0]']

 embedding_5 (Embedding)     (None, 1, 4)                 28        ['integer_lookup_19[0][0]']

 embedding_6 (Embedding)     (None, 1, 5)                 65        ['integer_lookup_20[0][0]']

 embedding_7 (Embedding)     (None, 1, 3)                 12        ['string_lookup_4[0][0]']

 embedding_8 (Embedding)     (None, 1, 3)                 18        ['string_lookup_5[0][0]']

 num (InputLayer)            [(None, 157)]                0         []

 reshape_18 (Reshape)        (None, 8)                    0         ['embedding[0][0]']

 reshape_19 (Reshape)        (None, 4)                    0         ['embedding_1[0][0]']

 reshape_20 (Reshape)        (None, 16)                   0         ['embedding_2[0][0]']

 reshape_21 (Reshape)        (None, 31)                   0         ['embedding_3[0][0]']

 reshape_22 (Reshape)        (None, 64)                   0         ['embedding_4[0][0]']

 reshape_23 (Reshape)        (None, 4)                    0         ['embedding_5[0][0]']

 reshape_24 (Reshape)        (None, 5)                    0         ['embedding_6[0][0]']

 reshape_25 (Reshape)        (None, 3)                    0         ['embedding_7[0][0]']

 reshape_26 (Reshape)        (None, 3)                    0         ['embedding_8[0][0]']

 normalization_3 (Normaliza  (None, 157)                  315       ['num[0][0]']
 tion)

 concatenate_2 (Concatenate  (None, 295)                  0         ['reshape_18[0][0]',
 )                                                                   'reshape_19[0][0]',
                                                                     'reshape_20[0][0]',
                                                                     'reshape_21[0][0]',
                                                                     'reshape_22[0][0]',
                                                                     'reshape_23[0][0]',
                                                                     'reshape_24[0][0]',
                                                                     'reshape_25[0][0]',
                                                                     'reshape_26[0][0]',
                                                                     'normalization_3[0][0]']

 dense_11 (Dense)            (None, 512)                  151552    ['concatenate_2[0][0]']

 batch_normalization_6 (Bat  (None, 512)                  2048      ['dense_11[0][0]']
 chNormalization)

 dropout_7 (Dropout)         (None, 512)                  0         ['batch_normalization_6[0][0]'
                                                                    ]

 dense_12 (Dense)            (None, 256)                  131328    ['dropout_7[0][0]']

 batch_normalization_7 (Bat  (None, 256)                  1024      ['dense_12[0][0]']
 chNormalization)

 dropout_8 (Dropout)         (None, 256)                  0         ['batch_normalization_7[0][0]'
                                                                    ]

 dense_13 (Dense)            (None, 100)                  25700     ['dropout_8[0][0]']

==================================================================================================
Total params: 1538746 (5.87 MB)
Trainable params: 1536895 (5.86 MB)
Non-trainable params: 1851 (7.23 KB)
__________________________________________________________________________________________________

In [55]:
callbacks = [
    tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=3, restore_best_weights=True),
    tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=2, min_lr=1e-5),
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=20,
    callbacks=callbacks,
    verbose=1
)

Epoch 1/20
98/98 [==============================] - 10s 80ms/step - loss: 4.0682 - sparse_categorical_accuracy: 0.0819 - val_loss: 3.6704 - val_sparse_categorical_accuracy: 0.1287 - lr: 8.0000e-04
Epoch 2/20
98/98 [==============================] - 9s 85ms/step - loss: 3.6128 - sparse_categorical_accuracy: 0.1123 - val_loss: 3.4612 - val_sparse_categorical_accuracy: 0.1396 - lr: 8.0000e-04
Epoch 3/20
98/98 [==============================] - 9s 88ms/step - loss: 3.4322 - sparse_categorical_accuracy: 0.1308 - val_loss: 3.3265 - val_sparse_categorical_accuracy: 0.1550 - lr: 8.0000e-04
Epoch 4/20
98/98 [==============================] - 10s 90ms/step - loss: 3.3093 - sparse_categorical_accuracy: 0.1484 - val_loss: 3.2255 - val_sparse_categorical_accuracy: 0.1678 - lr: 8.0000e-04
Epoch 5/20
98/98 [==============================] - 9s 89ms/step - loss: 3.2175 - sparse_categorical_accuracy: 0.1646 - val_loss: 3.1674 - val_sparse_categorical_accuracy: 0.1767 - lr: 8.0000e-04
Epoch 6/20
98/98 [==============================] - 10s 96ms/step - loss: 3.1477 - sparse_categorical_accuracy: 0.1789 - val_loss: 3.1282 - val_sparse_categorical_accuracy: 0.1816 - lr: 8.0000e-04
Epoch 7/20
98/98 [==============================] - 10s 99ms/step - loss: 3.0910 - sparse_categorical_accuracy: 0.1898 - val_loss: 3.1028 - val_sparse_categorical_accuracy: 0.1863 - lr: 8.0000e-04
Epoch 8/20
98/98 [==============================] - 11s 103ms/step - loss: 3.0442 - sparse_categorical_accuracy: 0.1972 - val_loss: 3.0886 - val_sparse_categorical_accuracy: 0.1873 - lr: 8.0000e-04
Epoch 9/20
98/98 [==============================] - 11s 101ms/step - loss: 3.0049 - sparse_categorical_accuracy: 0.2037 - val_loss: 3.0797 - val_sparse_categorical_accuracy: 0.1888 - lr: 8.0000e-04
Epoch 10/20
98/98 [==============================] - 11s 101ms/step - loss: 2.9721 - sparse_categorical_accuracy: 0.2083 - val_loss: 3.0719 - val_sparse_categorical_accuracy: 0.1910 - lr: 8.0000e-04
Epoch 11/20
98/98 [==============================] - 11s 102ms/step - loss: 2.9460 - sparse_categorical_accuracy: 0.2105 - val_loss: 3.0711 - val_sparse_categorical_accuracy: 0.1898 - lr: 8.0000e-04
Epoch 12/20
98/98 [==============================] - 11s 101ms/step - loss: 2.9231 - sparse_categorical_accuracy: 0.2135 - val_loss: 3.0655 - val_sparse_categorical_accuracy: 0.1919 - lr: 8.0000e-04
Epoch 13/20
98/98 [==============================] - 11s 104ms/step - loss: 2.9049 - sparse_categorical_accuracy: 0.2148 - val_loss: 3.0658 - val_sparse_categorical_accuracy: 0.1915 - lr: 8.0000e-04
Epoch 14/20
98/98 [==============================] - 11s 100ms/step - loss: 2.8892 - sparse_categorical_accuracy: 0.2166 - val_loss: 3.0626 - val_sparse_categorical_accuracy: 0.1918 - lr: 8.0000e-04
Epoch 15/20
98/98 [==============================] - 11s 103ms/step - loss: 2.8719 - sparse_categorical_accuracy: 0.2186 - val_loss: 3.0613 - val_sparse_categorical_accuracy: 0.1924 - lr: 8.0000e-04
Epoch 16/20
98/98 [==============================] - 11s 101ms/step - loss: 2.8599 - sparse_categorical_accuracy: 0.2189 - val_loss: 3.0591 - val_sparse_categorical_accuracy: 0.1925 - lr: 8.0000e-04
Epoch 17/20
98/98 [==============================] - 11s 106ms/step - loss: 2.8473 - sparse_categorical_accuracy: 0.2206 - val_loss: 3.0610 - val_sparse_categorical_accuracy: 0.1924 - lr: 8.0000e-04
Epoch 18/20
98/98 [==============================] - 11s 106ms/step - loss: 2.8367 - sparse_categorical_accuracy: 0.2208 - val_loss: 3.0597 - val_sparse_categorical_accuracy: 0.1922 - lr: 8.0000e-04
Epoch 19/20
98/98 [==============================] - 11s 105ms/step - loss: 2.8079 - sparse_categorical_accuracy: 0.2268 - val_loss: 3.0549 - val_sparse_categorical_accuracy: 0.1944 - lr: 4.0000e-04
Epoch 20/20
98/98 [==============================] - 11s 106ms/step - loss: 2.8004 - sparse_categorical_accuracy: 0.2270 - val_loss: 3.0557 - val_sparse_categorical_accuracy: 0.1934 - lr: 4.0000e-04

In [56]:
y_val_prob = model.predict(val_ds, verbose=0)
y_val_arr = y_val.to_numpy()

print("HIT@5:", hit_at_k(y_val_arr, y_val_prob, k=5))
print("MAP@5:", map_at_k(y_val_arr, y_val_prob, k=5))

HIT@5: 0.53103
MAP@5: 0.3127538333333206